---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-data
data:
  HOGEHOGE: FUGAFUGA
  temp.txt: |
    hogehoge
    fugafuga
    foo bar baz
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-data
stringData:
  password: 1mbb1G968fb1CUg
  credential.txt: |
    credential data
    sWIEpx9wUdrVizVq
    UxuZ8kTeXvzyOWLQ
    7QVJIN1OI5FhxT9e
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  containers:
  - image: alpine
    name: alpine
    command: ["tail", "-f", "/dev/null"]
    volumeMounts:
    - name: cm-volume
      mountPath: /config
    - name: secret-volume
      mountPath: /etc/secrets
    - name: secret-volume2
      mountPath: /secrets
  volumes:
  - name: cm-volume
    configMap:
      name: cm-data
  - name: secret-volume
    secret:
      secretName: secret-data
      defaultMode: 0600
      items:
      - key: credential.txt
        path: creds/secret.txt
        mode: 0400
  - name: secret-volume2
    secret:
      secretName: secret-data
  terminationGracePeriodSeconds: 0
